# Generated by Django 3.2.9 on 2021-11-29 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mascota_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('costo_total', models.IntegerField()),
                ('forma_pago', models.CharField(max_length=250)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'factura',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('tarifa', models.IntegerField()),
                ('descripcion', models.CharField(max_length=250, null=True)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'servicio',
            },
        ),
        migrations.CreateModel(
            name='HistoricoServicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tarifa', models.IntegerField()),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=1)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio_api.servicio')),
            ],
            options={
                'db_table': 'historialdeservicio',
            },
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=1)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascota_api.consulta')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio_api.factura')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio_api.servicio')),
            ],
            options={
                'db_table': 'historico',
            },
        ),
    ]
