# Generated by Django 3.2.9 on 2021-11-29 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250, unique=True)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250, unique=True)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'tipoidentificacion',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=254, unique=True)),
                ('clave', models.CharField(max_length=254)),
                ('identificacion', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=250)),
                ('apellidos', models.CharField(max_length=250)),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('telefono_fijo', models.CharField(max_length=30, null=True)),
                ('direccion', models.CharField(max_length=250)),
                ('estado', models.CharField(max_length=1)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario_api.rol')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario_api.tipoidentificacion')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evento', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(max_length=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario_api.usuario')),
            ],
            options={
                'db_table': 'historial',
            },
        ),
    ]
