# Generated by Django 3.2.9 on 2021-11-18 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=250, null=True)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'topoidentificacion',
            },
        ),
        migrations.CreateModel(
            name='IdentificacionCliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=250, unique=True)),
                ('estado', models.CharField(max_length=1)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente_api.tipoidentificacion')),
            ],
            options={
                'db_table': 'identificacioncliente',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('telefono_fijo', models.CharField(max_length=30, null=True)),
                ('direccion', models.CharField(max_length=250)),
                ('estado', models.CharField(max_length=1)),
                ('identificacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cliente_api.identificacioncliente')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuario_api.usuario')),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
    ]
