# Generated by Django 3.2.9 on 2021-11-29 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'color',
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'especie',
            },
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('tamanio', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'raza',
            },
        ),
        migrations.CreateModel(
            name='TipoConsulta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'tipoconsulta',
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('microchip', models.CharField(max_length=250, null=True, unique=True)),
                ('sexo', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=250)),
                ('fecha_nacimiento', models.DateField()),
                ('estado', models.CharField(max_length=1)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascota_api.color')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascota_api.especie')),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascota_api.raza')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario_api.usuario')),
            ],
            options={
                'db_table': 'mascota',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('peso', models.FloatField(null=True)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=250, null=True)),
                ('estado', models.CharField(max_length=1)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascota_api.mascota')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascota_api.tipoconsulta')),
            ],
            options={
                'db_table': 'consulta',
            },
        ),
    ]
