# Generated by Django 3.2.9 on 2021-11-18 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'color',
            },
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=250, null=True)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'enfermedad',
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'especie',
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('microchip', models.CharField(max_length=250, null=True)),
                ('nombre', models.CharField(max_length=250)),
                ('fecha_nacimiento', models.DateField()),
                ('imagen', models.CharField(max_length=250)),
                ('estado', models.CharField(max_length=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente_api.cliente')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascota_api.color')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascota_api.especie')),
            ],
            options={
                'db_table': 'mascota',
            },
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('tamanio', models.CharField(max_length=80)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'raza',
            },
        ),
        migrations.CreateModel(
            name='Padecimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=1)),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascota_api.enfermedad')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascota_api.mascota')),
            ],
            options={
                'db_table': 'padecimiento',
            },
        ),
        migrations.AddField(
            model_name='mascota',
            name='raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascota_api.raza'),
        ),
    ]
